### PR TITLE
Can't stream with react-dom

### PR DESCRIPTION
**Pull request by colinmeinke**

### CODE REVIEW

**Comment by colinmeinke** [comment]
Alternatively https://github.com/aickin/react-dom-stream

**Comment by lukemorton** [comment]
@colinmeinke How do you think we should serve the first load? Stream or not?

cc @zuren

**Comment by rrpff** [comment]
Go with streams, there should be noticeable performance gains on larger apps.

**Comment by lukemorton** [comment]
Cool. @colinmeinke seeing as you're doing nothing but eating in Mexico, do you mind amending your PR to implement streams? Make sure you squash the branch too.

**Comment by lukemorton** [comment]
Also can I just remind you to read The Republic by Plato before submitting a PR.

Check the contributing docs: https://github.com/drpheltright/republic/blob/master/doc/contributing.md

**Comment by colinmeinke** [comment]
Here we go

**Comment by lukemorton** [comment]
Thanks gonna get a bunch of npm deps on the go,

**Pull request merged**
